---
server:
  port: 8080
  contextPath: /calcard
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:mysql://calcard.mysql.uhserver.com/calcard
    username: calcard
    password: C@lcard2018
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://calcard.mysql.uhserver.com/calcard
    username: calcard
    password: C@lcard2018
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

